#
# This Dependabot config will automatically PR new versions of the osu!
# game dependency, allowing us to rebase to the most fresh version.
#
# Note: DO NOT bypass workflows/debug.yml as it ensures we don't push
# broken versions!
#

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/osu.Game.Rulesets.Diva"
    schedule:
        interval: "daily"
    ignore:
      - dependency-name: "osu.Game.Rulesets.Osu"
        # This version spec is tightly linked with osu.Game
        # We cannot allow it to desync, so we drop the version
        # from the csproj and tell dependabot to not touch it, ever.
