#
# This workflow triggers whenever a new tag is created which begins with v
# For example, a tag v42.0.1 will create a new version.
#

name: dotnet-release

on:
    push:
        tags:
            - 'v*'

jobs:
    dotnet-build:
        name: Generate release assets
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '9.0.x'
          - name: Build the release DLL
            run: dotnet publish -c Release osu.Game.Rulesets.Diva
          - name: Upload as asset
            uses: softprops/action-gh-release@v1
            with:
                files: osu.Game.Rulesets.Diva/bin/Release/*/osu.Game.Rulesets.Diva.dll
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

