name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dep:
    name: Bump Dependencies PR
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2

      - name: Bump nuget package version
        id: update-csproj
        run: |
          $jdata = curl --silent "https://api.github.com/repos/ppy/osu/releases/latest" | ConvertFrom-Json
          $latestVer = $jdata.tag_name
          $regex = '(?<=\"ppy\.osu\.Game.*\"\s*Version\s*=\s*\")(.*)(?=\")'
          (Get-Content osu.Game.Rulesets.Diva\osu.Game.Rulesets.Diva.csproj) -replace $regex, $latestVer | Set-Content osu.Game.Rulesets.Diva\osu.Game.Rulesets.Diva.csproj
          echo "::set-output name=version::$latestVer"

      - run: git --no-pager diff

      - name: Create PR
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: osu-bump-${{ steps.update-csproj.outputs.version }}
          commit-message: 'chore: update osu packages to ${{ steps.update-csproj.outputs.version }}'
          title: 'Update to osu! ${{ steps.update-csproj.outputs.version }}'
          base: master
          body: |
            #skip-changelog

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: Repository Maintenance
          delete-branch: true
