name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-dep:
    name: Bump Dependencies PR
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Bump nuget package version
        id: update-csproj
        run: |
          dotnet package update ppy.osu.Game --project osu.Game.Rulesets.Diva
          dotnet package update ppy.osu.Game.Rulesets.Osu --project osu.Game.Rulesets.Diva

      - run: git --no-pager diff

      - name: Create PR
        uses: peter-evans/create-pull-request@v6.0.1
        with:
          token: ${{ secrets.PAT }}
          branch: osu-bump
          commit-message: 'chore: update osu packages to ${{ steps.update-csproj.outputs.OSU_VERSION }}'
          title: 'Update to osu! ${{ steps.update-csproj.outputs.OSU_VERSION }}'
          base: master
          body: |
            #skip-changelog

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: dependencies
          delete-branch: true
